#!/bin/bash
echo "🔍 Debugging SEO Agent Server"
echo "============================"
echo ""
echo "Run these commands on your server to diagnose:"
echo ""
echo "# 1. Check if containers are running"
echo "docker-compose ps"
echo ""
echo "# 2. Check Flask app logs (last 50 lines)"
echo "docker-compose logs --tail=50 seo-agent"
echo ""
echo "# 3. Check if gevent is in the built image"
echo "docker exec seo-agent-seo-agent-1 pip list | grep gevent"
echo ""
echo "# 4. Try running Flask directly to see errors"
echo "docker exec -it seo-agent-seo-agent-1 python main.py"
echo ""
echo "# 5. Check Dockerfile CMD"
echo "docker exec seo-agent-seo-agent-1 cat /app/Dockerfile"